### ISSUE TITLE
Add will-change CSS attribute to project cards

### ISSUE THREAD

**Issue by micahlt** [BraydenTW/braydentw.io#1]
At the moment, the hover animation on the project cards section is rendered a bit jankily.  Adding the following CSS rule...

```css
will-change: color,background-color,border-color,text-decoration-color,fill,stroke,opacity,box-shadow,transform,filter,backdrop-filter,-webkit-text-decoration-color,-webkit-backdrop-filter;
```

...ensures that the animations will be prepared and GPU-accelerated!

**Comment by BraydenTW** [comment]
Thanks for the suggestion Micah! Do I have to add all of those property names? For example, I don’t change the fill or stroke ever.

**Comment by micahlt** [comment]
Nope, just add the properties you are transitioning!  I copied that snippet from the the `transition-property` rule that the browser rendered :)

**Comment by BraydenTW** [comment]
Sweet, thanks @micahlt !

**Comment by micahlt** [comment]
No problem!
