### ISSUE TITLE
add license

### ISSUE THREAD

**Issue by SkyBulk** [BraydenTW/braydentw.io#4]
it's a very interesting project!

Would you consider adding a license to this repository to specify under which terms this code can be used or if its possible to consider adding a permissive license?

**Comment by BraydenTW** [comment]
Hi @SkyBulk, I apologize for getting back to you so late. But for terms of your question, I have chosen to stick with what I have written in the [guidelines](https://github.com/BraydenTW/braydentw.io?tab=readme-ov-file#guidelines) of this project's README file.
